# Generated by Django 5.0.1 on 2024-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_question_qno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='co',
            field=models.CharField(max_length=100),
        ),
    ]
