# Generated by Django 5.0.1 on 2024-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_question_co'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qno',
            field=models.IntegerField(),
        ),
    ]
