# Generated by Django 5.0 on 2024-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='fraud_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fraud', models.BooleanField(default=False)),
            ],
        ),
    ]
